#!/bin/sh
# Provides: Vinylla

start() {
    echo "CRITICAL: S02vinylla is running now!" > /etc/init.d/vinylla.log
    /start.sh 
    echo "Service starting up"   
}

stop () {    
    echo "Service shutting down"
}

status () {
    echo "Everything looks good"
}

##case statement to be used to call functions##
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status 
        ;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        exit 5
esac
exit $?
